[build]
    publish = "client/public"
    command = "echo No build command"
    node_bundler = "esbuild"

[dev]
    publish = "client/public"
    node_bundler = "esbuild"

[[redirects]]
    from = "/*"
    to = "/.server/src/:splat"
    status = 200
